# Uncomment this file to enable multilanguage site support

[ca]
languageName = "Català"
languagedirection = "ltr"
title = "Pau Giuli"
weight = 2

[en]
languageName = "English"
languagedirection = "ltr"
title = "Pau Giuli"
weight = 1

